version: '2'

services:
  build:
    image: ${IMAGE}:latest
    build:
      context: latest
  major:
    extends: build
    image: ${IMAGE}:${MAJOR}
  minor:
    extends: build
    image: ${IMAGE}:${MAJOR}.${MINOR}
  patch:
    extends: build
    image: ${IMAGE}:${MAJOR}.${MINOR}.${PATCH}
